version: '2'

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
     - "6379:6379"

  mongodb:
    container_name: mongodb
    image: mongo:3.2.4
    ports:
      - "27017:27017"

  app11:
    container_name: app11
    environment:
      - COMPONENT_NAME="app11"
    ports:
      - "8011:8080"
    build:
      context: "./"
      dockerfile: Dockerfile.app1
    depends_on:
      - redis
    links:
      - redis

  app12:
    container_name: app12
    environment:
      - COMPONENT_NAME="app12"
    ports:
      - "8012:8080"
    build:
      context: "./"
      dockerfile: Dockerfile.app1
    depends_on:
      - redis
    links:
      - redis

  app21:
    container_name: app21
    environment:
      - COMPONENT_NAME="app21"
    ports:
      - "8021:8080"
    build:
      context: "./"
      dockerfile: Dockerfile.app2
    depends_on:
      - mongodb
    links:
      - mongodb

  app22:
    container_name: app22
    ports:
      - "8022:8080"
    environment:
      - COMPONENT_NAME="app22"
    build:
      context: "./"
      dockerfile: Dockerfile.app2
    depends_on:
      - mongodb
    links:
      - mongodb
